apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: streamingapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: 488347380015.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-admin:5
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
        envFrom:
        - configMapRef:
            name: streamingapp-config
        - secretRef:
            name: streamingapp-secret
