apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend
 namespace: streamingapp

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: 488347380015.dkr.ecr.ap-south-1.amazonaws.com/streamingapp-frontend:5

        imagePullPolicy: Always

        ports:
        - containerPort: 80

        envFrom:
        - configMapRef:
            name: streamingapp-config
        - secretRef:
            name: streamingapp-secret
