namespace: streamingapp

replicaCount: 2

accountId: ""
region: ap-south-1

imagePullPolicy: Always

images:
  auth:
    repository: streamingapp-auth
    tag: latest

  streaming:
    repository: streamingapp-streaming
    tag: latest

  admin:
    repository: streamingapp-admin
    tag: latest

  chat:
    repository: streamingapp-chat
    tag: latest

  frontend:
    repository: streamingapp-frontend
    tag: latest

service:
  auth: 3001
  streaming: 3002
  admin: 3003
  chat: 3004
  frontend: 80
  mongo: 27017
