apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      labels:
        app: auth

    spec:
      containers:
      - name: auth
        image: "{{ .Values.accountId }}.dkr.ecr.{{ .Values.region }}.amazonaws.com/{{ .Values.images.auth.repository }}:{{ .Values.images.auth.tag }}"

        imagePullPolicy: {{ .Values.imagePullPolicy }}

        ports:
        - containerPort: 3001

        envFrom:
        - configMapRef:
            name: streamingapp-config
        - secretRef:
            name: streamingapp-secret
