apiVersion: apps/v1
kind: Deployment
metadata:
 name: chat
 namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: chat

  template:
    metadata:
      labels:
        app: chat

    spec:
      containers:
      - name: chat
        image: "{{ .Values.accountId }}.dkr.ecr.{{ .Values.region }}.amazonaws.com/{{ .Values.images.chat.repository }}:{{ .Values.images.chat.tag }}"

        imagePullPolicy: {{ .Values.imagePullPolicy }}

        ports:
        - containerPort: 3004

        envFrom:
        - configMapRef:
            name: streamingapp-config
        - secretRef:
            name: streamingapp-secret
